services:
  # auth
  auth:
    build: ./auth
    ports:
      - "8001:8000"
    networks:
      - microservicios-net
    env_file:
      - ./.env
    depends_on:
      - auth-db
    restart: always

  auth-db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    restart: always

  # productos
  productos:
    build: ./productos/
    ports:
      - "8002:8000"
    networks:
      - microservicios-net
    env_file:
      - ./.env
    depends_on:
      - productos-db
    restart: always

  productos-db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    restart: always

  # inventario
  inventario:
    build: ./inventario
    ports:
      - "8003:8000"
    networks:
      - microservicios-net
    env_file:
      - ./.env
    depends_on:
      - inventario-db
    restart: always

  inventario-db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    restart: always

  # pedidos
  pedidos:
    build: ./pedidos
    ports:
      - "8004:8000"
    networks:
      - microservicios-net
    env_file:
      - ./.env
    depends_on:
      - pedidos-db
    restart: always

  pedidos-db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    restart: always
